"""initial migration

Revision ID: 3a9efc2abe71
Revises: 
Create Date: 2018-05-08 23:58:25.294342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a9efc2abe71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='department')
    op.drop_table('department')
    op.drop_table('user_name1')
    op.drop_table('post_tags')
    op.drop_table('admin')
    op.drop_table('demo2')
    op.drop_table('demo3')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_table('demo')
    op.drop_table('data')
    op.drop_table('post')
    op.drop_table('comment')
    op.drop_table('user_name')
    op.drop_table('tag')
    op.drop_table('order_ticket')
    op.add_column('payorders', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payorders', 'member_since')
    op.create_table('order_ticket',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Ticket', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('OpenTime', mysql.DATETIME(), nullable=True),
    sa.Column('Type', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Size', mysql.FLOAT(), nullable=True),
    sa.Column('Item', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('OpenPrice', mysql.FLOAT(), nullable=True),
    sa.Column('CloseTime', mysql.DATETIME(), nullable=True),
    sa.Column('ClosePrice', mysql.FLOAT(), nullable=True),
    sa.Column('Swap', mysql.FLOAT(), nullable=True),
    sa.Column('Profit', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('user_name',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('emai', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('comfired', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('hash_password', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='comment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('publish_date', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_name1.id'], name='post_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('data',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8', length=100), nullable=True),
    sa.Column('resourcedata', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activenumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pernumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activrpersent', mysql.FLOAT(), nullable=True),
    sa.Column('losspersent', mysql.FLOAT(), nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('demo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('salary', mysql.FLOAT(precision=255, scale=2), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('agreement', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_table('demo3',
    sa.Column('id', mysql.INTEGER(display_width=255), nullable=False),
    sa.Column('img', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('demo2',
    sa.Column('id', mysql.INTEGER(display_width=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('way', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('product', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('time', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(display_width=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(charset='utf8', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('post_tags',
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_tags_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='post_tags_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('user_name1',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('eamil', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('department',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'department', ['name'], unique=True)
    # ### end Alembic commands ###
