version: "3"
services:

  db:
    image: mysql:5.7
    networks:
      - lenna-work
    environment:
      MYSQL_ROOT_PASSWORD: lenna520
      MYSQL_DATABASE: test
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis
    ports:
    - "6379"
    networks:
    - lenna-work
    deploy:
      placement:
        constraints: [node.role == manager]
  scrapy:
    image: myspider:v1
    networks:
      - lenna-work
    command: python3 main.py
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 6
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  lenna-work:

